package ast;

/**
 * An enum to declare type of an AST node
 */
public enum NodeType {
    /*Mathematics operations*/
    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    MOD,
    ARITHMETIC_AND,
    ARITHMETIC_OR,
    XOR,
    POST_DECREMENT,
    POST_INCREMENT,
    PRE_INCREMENT,
    PRE_DECREMENT,
    UNARY_MINUS,
    UNARY_PLUS,
    /*Condition operations*/
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    EQUAL,
    NOT_EQUAL,
    /*Logical operations*/
    BOOLEAN_AND,
    BOOLEAN_NOT,
    BOOLEAN_OR,
    /*Literals*/
    BOOLEAN_LITERAL,
    CHAR_LITERAL,
    INTEGER_LITERAL,
    NULL_LITERAL,
    FLOAT_LITERAL,
    STRING_LITERAL,
    LONG_LITERAL,
    /*Types*/
    BOOLEAN_TYPE,
    DOUBLE_TYPE,
    CHAR_TYPE,
    INT_TYPE,
    FLOAT_TYPE,
    LONG_TYPE,
    STRING_TYPE,
    VOID,
    AUTO_TYPE,
    /*Declarations*/
    FIELD_DECLARATION,
    LOCAL_VAR_DECLARATION,
    VARIABLE_DECLARATIONS,
    VARIABLE_DECLARATION,
    METHOD_DECLARATION,
    STRUCT_DECLARATION,
    DECLARATIONS,

    ARGUMENTS,

    CAST,
    CLASS,
    CLASS_BODY,
    EMPTY_STATEMENT,
    EXPRESSION_STATEMENT,
    IDENTIFIER,
    IF_STATEMENT,
    METHOD_ACCESS,
    PARAMETER,
    PARAMETERS,
    ASSIGN,
    BLOCK,
    RETURN_STATEMENT,
    VAR_USE,
    WHILE_STATEMENT,
    START
}
