/* The following code was generated by JFlex 1.7.0 */

package scanner;

import java_cup.runtime.*;
import parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\4\1\6\1\7\1\5\22\0\1\15\1\47\1\72"+
    "\1\13\1\0\1\57\1\53\1\73\1\62\1\63\1\56\1\12\1\65"+
    "\1\3\1\64\1\14\1\75\11\2\1\66\1\67\1\50\1\46\1\51"+
    "\2\0\4\1\1\11\6\1\1\45\1\1\1\43\6\1\1\44\5\1"+
    "\1\70\1\74\1\71\1\55\1\1\1\0\1\26\1\16\1\21\1\31"+
    "\1\10\1\33\1\34\1\36\1\32\1\1\1\27\1\20\1\1\1\22"+
    "\1\17\1\42\1\1\1\25\1\23\1\24\1\30\1\37\1\35\1\41"+
    "\1\1\1\40\1\60\1\54\1\61\1\52\6\0\1\6\u1fa2\0\1\6"+
    "\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\0\1\2\1\3\1\4\1\5\2\6"+
    "\1\3\1\7\1\2\1\10\17\3\1\11\1\2\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\1\1\36\1\37\1\2\1\40"+
    "\1\2\2\0\1\41\1\42\3\3\1\43\1\44\1\6"+
    "\1\0\1\45\3\3\1\46\1\47\21\3\1\50\6\3"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\40\1\0"+
    "\1\67\2\0\1\3\1\70\1\3\1\0\7\3\1\71"+
    "\10\3\1\72\4\3\1\73\1\74\5\3\2\0\1\75"+
    "\1\3\1\6\1\3\1\76\1\3\1\77\2\3\1\100"+
    "\1\101\1\102\3\3\1\103\3\3\1\104\6\3\1\105"+
    "\1\67\1\0\1\3\1\106\1\107\1\110\7\3\1\111"+
    "\2\3\1\112\1\113\1\3\1\114\1\3\1\115\1\116"+
    "\1\117\1\120\1\121\1\122\1\3\1\123\2\3\1\124"+
    "\1\3\1\125\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\u0174\0\272"+
    "\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364"+
    "\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554"+
    "\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744"+
    "\0\272\0\272\0\272\0\272\0\u0782\0\272\0\272\0\272"+
    "\0\272\0\272\0\272\0\272\0\272\0\272\0\272\0\272"+
    "\0\272\0\272\0\u07c0\0\272\0\u07fe\0\u083c\0\u083c\0\u087a"+
    "\0\u08b8\0\u08f6\0\272\0\272\0\u0934\0\u0972\0\u09b0\0\272"+
    "\0\272\0\u09ee\0\u0a2c\0\272\0\u0a6a\0\u0aa8\0\u0ae6\0\370"+
    "\0\370\0\u0b24\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98"+
    "\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88"+
    "\0\u0ec6\0\u0f04\0\370\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\u103a"+
    "\0\u1078\0\272\0\272\0\272\0\272\0\272\0\272\0\272"+
    "\0\272\0\272\0\272\0\272\0\272\0\272\0\272\0\272"+
    "\0\u083c\0\u10b6\0\u10f4\0\u1132\0\u1170\0\370\0\u11ae\0\u11ec"+
    "\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360\0\u139e\0\370"+
    "\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512\0\u1550\0\u158e"+
    "\0\370\0\u15cc\0\u160a\0\u1648\0\u1686\0\370\0\370\0\u16c4"+
    "\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838\0\370\0\u1876"+
    "\0\u0a2c\0\u18b4\0\370\0\u18f2\0\370\0\u1930\0\u196e\0\370"+
    "\0\370\0\370\0\u19ac\0\u19ea\0\u1a28\0\370\0\u1a66\0\u1aa4"+
    "\0\u1ae2\0\370\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56"+
    "\0\370\0\u1838\0\u1c94\0\u1cd2\0\370\0\370\0\370\0\u1d10"+
    "\0\u1d4e\0\u1d8c\0\u1dca\0\u1e08\0\u1e46\0\u1e84\0\370\0\u1ec2"+
    "\0\u1f00\0\370\0\370\0\u1f3e\0\370\0\u1f7c\0\370\0\370"+
    "\0\370\0\370\0\370\0\370\0\u1fba\0\370\0\u1ff8\0\u2036"+
    "\0\370\0\u2074\0\370\0\370";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\4\1\10"+
    "\1\12\1\5\1\13\1\14\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\5"+
    "\1\27\1\30\1\31\1\32\3\5\1\33\3\5\1\34"+
    "\2\5\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\4"+
    "\1\6\4\63\2\4\64\63\1\64\1\63\1\65\1\63"+
    "\73\66\1\67\1\70\1\66\77\0\2\5\5\0\2\5"+
    "\4\0\30\5\27\0\1\5\2\71\1\6\1\71\4\0"+
    "\2\72\63\71\1\6\2\0\1\6\1\73\42\0\1\74"+
    "\26\0\1\6\4\0\1\10\72\0\2\5\5\0\2\5"+
    "\4\0\2\5\1\75\1\5\1\76\16\5\1\77\4\5"+
    "\27\0\1\5\2\0\1\6\7\0\1\100\33\0\1\101"+
    "\26\0\1\6\13\0\1\102\75\0\1\103\32\0\1\104"+
    "\30\0\2\5\5\0\1\105\1\5\4\0\1\5\1\106"+
    "\5\5\1\107\20\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\7\5\1\110\5\5\1\111\12\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\1\5\1\112"+
    "\26\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\1\5\1\113\6\5\1\114\7\5\1\115\7\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\1\5\1\116"+
    "\10\5\1\117\15\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\6\5\1\120\5\5\1\121\2\5\1\122"+
    "\10\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\7\5\1\123\20\5\27\0\1\5\1\0\2\5\5\0"+
    "\1\124\1\5\4\0\30\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\4\5\1\125\5\5\1\126\15\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\4\5"+
    "\1\127\23\5\27\0\1\5\1\0\2\5\5\0\1\130"+
    "\1\5\4\0\1\5\1\131\26\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\132\10\5\1\133"+
    "\12\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\1\5\1\134\1\135\5\5\1\136\1\5\1\137\15\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\1\5"+
    "\1\140\26\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\26\5\1\141\1\5\27\0\1\5\46\0\1\142"+
    "\75\0\1\143\75\0\1\144\75\0\1\145\75\0\1\146"+
    "\27\0\4\63\2\0\64\63\1\0\1\63\1\0\1\63"+
    "\16\0\1\147\3\0\1\150\1\0\1\151\1\152\5\0"+
    "\1\153\3\0\1\154\32\0\1\155\1\156\1\0\1\157"+
    "\73\0\1\160\20\0\1\161\3\0\1\161\1\0\2\161"+
    "\5\0\1\161\3\0\1\161\32\0\1\161\1\67\2\161"+
    "\2\0\1\162\1\163\6\0\1\163\62\0\1\162\2\0"+
    "\1\162\1\164\6\0\1\164\62\0\1\162\1\0\2\5"+
    "\5\0\2\5\4\0\5\5\1\165\22\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\13\5\1\166\14\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\167\21\5\27\0\1\5\4\102\2\0\70\102\13\103"+
    "\1\170\62\103\1\0\2\5\5\0\2\5\4\0\16\5"+
    "\1\171\11\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\1\5\1\172\26\5\27\0\1\5\1\0\2\5"+
    "\5\0\1\173\1\5\4\0\30\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\174\23\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\4\5\1\175"+
    "\23\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\5\5\1\176\22\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\10\5\1\177\17\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\6\5\1\200\21\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\2\5\1\201"+
    "\25\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\7\5\1\202\20\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\22\5\1\203\5\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\14\5\1\204\13\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\12\5\1\205"+
    "\15\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\3\5\1\206\2\5\1\207\15\5\1\210\3\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\13\5\1\211"+
    "\14\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\6\5\1\212\21\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\6\5\1\213\21\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\15\5\1\214\12\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\12\5\1\215"+
    "\15\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\6\5\1\216\21\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\7\5\1\217\20\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\1\5\1\220\26\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\2\5\1\221"+
    "\25\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\4\5\1\222\23\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\14\5\1\223\13\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\27\5\1\224\27\0\1\5"+
    "\2\0\1\162\5\0\2\225\63\0\1\162\2\0\1\162"+
    "\72\0\1\162\2\0\1\162\1\226\6\0\1\226\62\0"+
    "\1\162\1\0\2\5\5\0\1\227\1\5\4\0\30\5"+
    "\27\0\1\5\1\0\2\5\5\0\1\230\1\5\4\0"+
    "\30\5\27\0\1\5\13\103\1\170\1\231\61\103\1\0"+
    "\2\5\5\0\2\5\4\0\14\5\1\232\13\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\2\5\1\233"+
    "\25\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\10\5\1\234\17\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\16\5\1\235\11\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\5\5\1\236\1\237\21\5"+
    "\27\0\1\5\1\0\2\5\5\0\1\240\1\5\4\0"+
    "\30\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\7\5\1\241\20\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\2\5\1\242\25\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\14\5\1\243\13\5\27\0"+
    "\1\5\1\0\2\5\5\0\1\244\1\5\4\0\30\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\245\21\5\27\0\1\5\1\0\2\5\5\0\1\246"+
    "\1\5\4\0\30\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\1\5\1\247\26\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\12\5\1\250\15\5\27\0"+
    "\1\5\1\0\2\5\5\0\1\251\1\5\4\0\30\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\1\5"+
    "\1\252\26\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\14\5\1\253\13\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\10\5\1\254\17\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\1\255\27\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\10\5\1\256"+
    "\17\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\5\5\1\257\22\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\3\5\1\260\24\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\13\5\1\261\14\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\27\5\1\242"+
    "\27\0\1\5\2\0\1\262\1\263\6\0\1\263\62\0"+
    "\1\262\2\0\1\262\72\0\1\262\1\0\2\5\5\0"+
    "\2\5\4\0\7\5\1\264\20\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\265\23\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\11\5\1\266"+
    "\16\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\6\5\1\267\21\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\14\5\1\270\13\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\271\23\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\1\5\1\272"+
    "\26\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\3\5\1\273\24\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\7\5\1\274\20\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\7\5\1\275\20\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\10\5\1\276"+
    "\17\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\2\5\1\277\25\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\12\5\1\300\15\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\2\5\1\301\25\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\6\5\1\302"+
    "\21\5\27\0\1\5\1\0\2\5\5\0\1\303\1\5"+
    "\4\0\30\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\6\5\1\304\21\5\27\0\1\5\2\0\1\262"+
    "\1\226\6\0\1\226\62\0\1\262\1\0\2\5\5\0"+
    "\2\5\4\0\4\5\1\305\23\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\306\23\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\16\5\1\307"+
    "\11\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\15\5\1\310\12\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\20\5\1\311\7\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\13\5\1\312\14\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\4\5\1\313"+
    "\23\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\6\5\1\314\21\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\2\5\1\315\25\5\27\0\1\5\1\0"+
    "\2\5\5\0\1\316\1\5\4\0\30\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\14\5\1\317\13\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\12\5"+
    "\1\320\15\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\6\5\1\321\21\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\1\5\1\322\26\5\27\0\1\5"+
    "\1\0\2\5\5\0\1\323\1\5\4\0\30\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\4\5\1\324"+
    "\23\5\27\0\1\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8370];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\0\1\11\3\1\1\11\30\1\4\11"+
    "\1\1\15\11\1\1\1\11\4\1\2\0\2\11\3\1"+
    "\2\11\1\1\1\0\1\11\35\1\17\11\1\0\1\1"+
    "\2\0\3\1\1\0\34\1\2\0\34\1\1\0\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuilder string;
    StringBuilder character;

    private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
    	return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol scanFunction() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }  // fall though
            case 213: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { string.append( yytext() );
            } 
            // fall through
          case 87: break;
          case 2: 
            { throw new Error("Illegal character <" + yytext() + ">");
            } 
            // fall through
          case 88: break;
          case 3: 
            { return symbol(sym.ID, new String(yytext()));
            } 
            // fall through
          case 89: break;
          case 4: 
            { return symbol(sym.INTCONST, new Integer(yytext()));
            } 
            // fall through
          case 90: break;
          case 5: 
            { return symbol(sym.MINUS);
            } 
            // fall through
          case 91: break;
          case 6: 
            { 
            } 
            // fall through
          case 92: break;
          case 7: 
            { return symbol(sym.ADD);
            } 
            // fall through
          case 93: break;
          case 8: 
            { return symbol(sym.DIV);
            } 
            // fall through
          case 94: break;
          case 9: 
            { return symbol(sym.ASSIGN);
            } 
            // fall through
          case 95: break;
          case 10: 
            { return symbol(sym.LESS);
            } 
            // fall through
          case 96: break;
          case 11: 
            { return symbol(sym.GR);
            } 
            // fall through
          case 97: break;
          case 12: 
            { return symbol(sym.BITNEG);
            } 
            // fall through
          case 98: break;
          case 13: 
            { return symbol(sym.ARITHAND);
            } 
            // fall through
          case 99: break;
          case 14: 
            { return symbol(sym.ARITHOR);
            } 
            // fall through
          case 100: break;
          case 15: 
            { return symbol(sym.XOR);
            } 
            // fall through
          case 101: break;
          case 16: 
            { return symbol(sym.PROD);
            } 
            // fall through
          case 102: break;
          case 17: 
            { return symbol(sym.MOD);
            } 
            // fall through
          case 103: break;
          case 18: 
            { return symbol(sym.LCURLY);
            } 
            // fall through
          case 104: break;
          case 19: 
            { return symbol(sym.RCURLY);
            } 
            // fall through
          case 105: break;
          case 20: 
            { return symbol(sym.LPAREN);
            } 
            // fall through
          case 106: break;
          case 21: 
            { return symbol(sym.RPAREN);
            } 
            // fall through
          case 107: break;
          case 22: 
            { return symbol(sym.DOT);
            } 
            // fall through
          case 108: break;
          case 23: 
            { return symbol(sym.COMMA);
            } 
            // fall through
          case 109: break;
          case 24: 
            { return symbol(sym.COLON);
            } 
            // fall through
          case 110: break;
          case 25: 
            { return symbol(sym.SEMICOLON);
            } 
            // fall through
          case 111: break;
          case 26: 
            { return symbol(sym.LBRACK);
            } 
            // fall through
          case 112: break;
          case 27: 
            { return symbol(sym.RBRACK);
            } 
            // fall through
          case 113: break;
          case 28: 
            { string = new StringBuilder("\""); yybegin(STRING);
            } 
            // fall through
          case 114: break;
          case 29: 
            { character = new StringBuilder("\'"); yybegin(CHAR);
            } 
            // fall through
          case 115: break;
          case 30: 
            { string.append("\"");
	    yybegin(YYINITIAL);
	    return symbol(sym.STRINGCONST, new String(string.toString()));
            } 
            // fall through
          case 116: break;
          case 31: 
            { string.append("\\");
            } 
            // fall through
          case 117: break;
          case 32: 
            { character.append(yytext());
	    yybegin(YYINITIAL);
	    return symbol(sym.CHARCONST, new Character(character.toString().charAt(1)));
            } 
            // fall through
          case 118: break;
          case 33: 
            { return symbol(sym.DEC);
            } 
            // fall through
          case 119: break;
          case 34: 
            { return symbol(sym.SUBASS);
            } 
            // fall through
          case 120: break;
          case 35: 
            { return symbol(sym.INC);
            } 
            // fall through
          case 121: break;
          case 36: 
            { return symbol(sym.ADDASS);
            } 
            // fall through
          case 122: break;
          case 37: 
            { return symbol(sym.DIVASS);
            } 
            // fall through
          case 123: break;
          case 38: 
            { return symbol(sym.LOGICOR);
            } 
            // fall through
          case 124: break;
          case 39: 
            { return symbol(sym.OF);
            } 
            // fall through
          case 125: break;
          case 40: 
            { return symbol(sym.IF);
            } 
            // fall through
          case 126: break;
          case 41: 
            { return symbol(sym.EQ);
            } 
            // fall through
          case 127: break;
          case 42: 
            { return symbol(sym.NOTEQ);
            } 
            // fall through
          case 128: break;
          case 43: 
            { return symbol(sym.LESSEQ);
            } 
            // fall through
          case 129: break;
          case 44: 
            { return symbol(sym.GREQ);
            } 
            // fall through
          case 130: break;
          case 45: 
            { return symbol(sym.MULTASS);
            } 
            // fall through
          case 131: break;
          case 46: 
            { string.append("\\b");
            } 
            // fall through
          case 132: break;
          case 47: 
            { string.append("\\n");
            } 
            // fall through
          case 133: break;
          case 48: 
            { string.append("\\t");
            } 
            // fall through
          case 134: break;
          case 49: 
            { string.append("\\r");
            } 
            // fall through
          case 135: break;
          case 50: 
            { string.append("\\f");
            } 
            // fall through
          case 136: break;
          case 51: 
            { string.append("\\v");
            } 
            // fall through
          case 137: break;
          case 52: 
            { string.append("\\\"");
            } 
            // fall through
          case 138: break;
          case 53: 
            { string.append("\\\'");
            } 
            // fall through
          case 139: break;
          case 54: 
            { string.append("\\0");
            } 
            // fall through
          case 140: break;
          case 55: 
            { return symbol(sym.REALCONST, new Double(yytext()));
            } 
            // fall through
          case 141: break;
          case 56: 
            { return symbol(sym.END);
            } 
            // fall through
          case 142: break;
          case 57: 
            { return symbol(sym.NOT);
            } 
            // fall through
          case 143: break;
          case 58: 
            { return symbol(sym.LOGICAND);
            } 
            // fall through
          case 144: break;
          case 59: 
            { return symbol(sym.INT);
            } 
            // fall through
          case 145: break;
          case 60: 
            { return symbol(sym.FOR);
            } 
            // fall through
          case 146: break;
          case 61: 
            { return symbol(sym.ELSE);
            } 
            // fall through
          case 147: break;
          case 62: 
            { return symbol(sym.BOOL);
            } 
            // fall through
          case 148: break;
          case 63: 
            { return symbol(sym.LONG);
            } 
            // fall through
          case 149: break;
          case 64: 
            { return symbol(sym.CASE);
            } 
            // fall through
          case 150: break;
          case 65: 
            { return symbol(sym.CHAR);
            } 
            // fall through
          case 151: break;
          case 66: 
            { return symbol(sym.NULL);
            } 
            // fall through
          case 152: break;
          case 67: 
            { return symbol(sym.TRUE);
            } 
            // fall through
          case 153: break;
          case 68: 
            { return symbol(sym.AUTO);
            } 
            // fall through
          case 154: break;
          case 69: 
            { return symbol(sym.VOID);
            } 
            // fall through
          case 155: break;
          case 70: 
            { return symbol(sym.BEGIN);
            } 
            // fall through
          case 156: break;
          case 71: 
            { return symbol(sym.BREAK);
            } 
            // fall through
          case 157: break;
          case 72: 
            { return symbol(sym.CONST);
            } 
            // fall through
          case 158: break;
          case 73: 
            { return symbol(sym.UNTIL);
            } 
            // fall through
          case 159: break;
          case 74: 
            { return symbol(sym.FLOAT);
            } 
            // fall through
          case 160: break;
          case 75: 
            { return symbol(sym.FALSE);
            } 
            // fall through
          case 161: break;
          case 76: 
            { return symbol(sym.EXTERN);
            } 
            // fall through
          case 162: break;
          case 77: 
            { return symbol(sym.STRING);
            } 
            // fall through
          case 163: break;
          case 78: 
            { return symbol(sym.SIZEOF);
            } 
            // fall through
          case 164: break;
          case 79: 
            { return symbol(sym.SWITCH);
            } 
            // fall through
          case 165: break;
          case 80: 
            { return symbol(sym.RECORD);
            } 
            // fall through
          case 166: break;
          case 81: 
            { return symbol(sym.RETURN);
            } 
            // fall through
          case 167: break;
          case 82: 
            { return symbol(sym.REPEAT);
            } 
            // fall through
          case 168: break;
          case 83: 
            { return symbol(sym.DOUBLE);
            } 
            // fall through
          case 169: break;
          case 84: 
            { return symbol(sym.DEFAULT);
            } 
            // fall through
          case 170: break;
          case 85: 
            { return symbol(sym.CONTINUE);
            } 
            // fall through
          case 171: break;
          case 86: 
            { return symbol(sym.FUNCTION);
            } 
            // fall through
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
