/* The following code was generated by JFlex 1.7.0 */

package scanner;

import java_cup.runtime.*;
import parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\4\1\6\1\7\1\5\22\0\1\15\1\46\1\71"+
    "\1\13\1\0\1\56\1\52\1\72\1\61\1\62\1\55\1\12\1\64"+
    "\1\3\1\63\1\14\1\74\11\2\1\65\1\66\1\47\1\45\1\50"+
    "\2\0\4\1\1\11\6\1\1\44\1\1\1\42\6\1\1\43\5\1"+
    "\1\67\1\73\1\70\1\54\1\1\1\0\1\26\1\16\1\21\1\31"+
    "\1\10\1\33\1\34\1\36\1\32\1\1\1\27\1\20\1\1\1\22"+
    "\1\17\2\1\1\25\1\23\1\24\1\30\1\37\1\35\1\41\1\1"+
    "\1\40\1\57\1\53\1\60\1\51\6\0\1\6\u1fa2\0\1\6\1\6"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\0\1\2\1\3\1\4\1\5\2\6"+
    "\1\3\1\7\1\2\1\10\16\3\1\11\1\2\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\1\1\36\1\37\1\2\1\40"+
    "\1\2\2\0\1\41\1\42\3\3\1\43\1\44\1\6"+
    "\1\0\1\45\3\3\1\46\20\3\1\47\6\3\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\40\1\0\1\66"+
    "\2\0\1\3\1\67\1\3\1\0\7\3\1\70\7\3"+
    "\1\71\3\3\1\72\1\73\5\3\2\0\1\74\1\3"+
    "\1\6\1\3\1\75\1\3\1\76\2\3\1\77\1\100"+
    "\1\101\3\3\1\102\2\3\1\103\5\3\1\104\1\66"+
    "\1\0\1\3\1\105\1\106\1\107\10\3\1\110\1\111"+
    "\1\3\1\112\1\3\1\113\1\114\1\115\1\116\1\117"+
    "\1\3\1\120\2\3\1\121\1\3\1\122\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\267"+
    "\0\u01ab\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319\0\u0356"+
    "\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501\0\u053e"+
    "\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9\0\267"+
    "\0\267\0\267\0\267\0\u0726\0\267\0\267\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\u0763\0\267\0\u07a0\0\u07dd\0\u07dd\0\u081a\0\u0857"+
    "\0\u0894\0\267\0\267\0\u08d1\0\u090e\0\u094b\0\267\0\267"+
    "\0\u0988\0\u09c5\0\267\0\u0a02\0\u0a3f\0\u0a7c\0\364\0\u0ab9"+
    "\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1"+
    "\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\364"+
    "\0\u0e89\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\u07dd\0\u0ff7\0\u1034"+
    "\0\u1071\0\u10ae\0\364\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df"+
    "\0\u121c\0\u1259\0\u1296\0\u12d3\0\364\0\u1310\0\u134d\0\u138a"+
    "\0\u13c7\0\u1404\0\u1441\0\u147e\0\364\0\u14bb\0\u14f8\0\u1535"+
    "\0\364\0\364\0\u1572\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3"+
    "\0\u16e0\0\364\0\u171d\0\u09c5\0\u175a\0\364\0\u1797\0\364"+
    "\0\u17d4\0\u1811\0\364\0\364\0\364\0\u184e\0\u188b\0\u18c8"+
    "\0\364\0\u1905\0\u1942\0\364\0\u197f\0\u19bc\0\u19f9\0\u1a36"+
    "\0\u1a73\0\364\0\u16e0\0\u1ab0\0\u1aed\0\364\0\364\0\364"+
    "\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c98\0\u1cd5"+
    "\0\364\0\364\0\u1d12\0\364\0\u1d4f\0\364\0\364\0\364"+
    "\0\364\0\364\0\u1d8c\0\364\0\u1dc9\0\u1e06\0\364\0\u1e43"+
    "\0\364\0\364";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\4\1\10"+
    "\1\12\1\5\1\13\1\14\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\2\5"+
    "\1\27\1\30\1\31\3\5\1\32\2\5\1\33\2\5"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\4\1\6"+
    "\4\62\2\4\63\62\1\63\1\62\1\64\1\62\72\65"+
    "\1\66\1\67\1\65\76\0\2\5\5\0\2\5\4\0"+
    "\27\5\27\0\1\5\2\70\1\6\1\70\4\0\2\71"+
    "\62\70\1\6\2\0\1\6\1\72\41\0\1\73\26\0"+
    "\1\6\4\0\1\10\71\0\2\5\5\0\2\5\4\0"+
    "\2\5\1\74\1\5\1\75\16\5\1\76\3\5\27\0"+
    "\1\5\2\0\1\6\7\0\1\77\32\0\1\100\26\0"+
    "\1\6\13\0\1\101\74\0\1\102\31\0\1\103\30\0"+
    "\2\5\5\0\1\104\1\5\4\0\1\5\1\105\5\5"+
    "\1\106\17\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\7\5\1\107\17\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\1\5\1\110\25\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\1\5\1\111\6\5"+
    "\1\112\7\5\1\113\6\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\1\5\1\114\10\5\1\115\14\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\116\5\5\1\117\2\5\1\120\7\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\7\5\1\121\17\5"+
    "\27\0\1\5\1\0\2\5\5\0\1\122\1\5\4\0"+
    "\27\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\4\5\1\123\5\5\1\124\14\5\27\0\1\5\1\0"+
    "\2\5\5\0\1\125\1\5\4\0\1\5\1\126\25\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\4\5"+
    "\1\127\10\5\1\130\11\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\1\5\1\131\1\132\5\5\1\133"+
    "\1\5\1\134\14\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\1\5\1\135\25\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\25\5\1\136\1\5\27\0"+
    "\1\5\45\0\1\137\74\0\1\140\74\0\1\141\74\0"+
    "\1\142\74\0\1\143\27\0\4\62\2\0\63\62\1\0"+
    "\1\62\1\0\1\62\16\0\1\144\3\0\1\145\1\0"+
    "\1\146\1\147\5\0\1\150\3\0\1\151\31\0\1\152"+
    "\1\153\1\0\1\154\72\0\1\155\20\0\1\156\3\0"+
    "\1\156\1\0\2\156\5\0\1\156\3\0\1\156\31\0"+
    "\1\156\1\66\2\156\2\0\1\157\1\160\6\0\1\160"+
    "\61\0\1\157\2\0\1\157\1\161\6\0\1\161\61\0"+
    "\1\157\1\0\2\5\5\0\2\5\4\0\5\5\1\162"+
    "\21\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\13\5\1\163\13\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\6\5\1\164\20\5\27\0\1\5\4\101"+
    "\2\0\67\101\13\102\1\165\61\102\1\0\2\5\5\0"+
    "\2\5\4\0\16\5\1\166\10\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\1\5\1\167\25\5\27\0"+
    "\1\5\1\0\2\5\5\0\1\170\1\5\4\0\27\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\4\5"+
    "\1\171\22\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\4\5\1\172\22\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\5\5\1\173\21\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\10\5\1\174\16\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\175\20\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\2\5\1\176\24\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\7\5\1\177\17\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\22\5\1\200\4\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\14\5"+
    "\1\201\12\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\12\5\1\202\14\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\3\5\1\203\2\5\1\204\20\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\13\5"+
    "\1\205\13\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\6\5\1\206\20\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\15\5\1\207\11\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\12\5\1\210\14\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\211\20\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\7\5\1\212\17\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\1\5\1\213\25\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\2\5\1\214\24\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\4\5"+
    "\1\215\22\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\14\5\1\216\12\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\26\5\1\217\27\0\1\5\2\0"+
    "\1\157\5\0\2\220\62\0\1\157\2\0\1\157\71\0"+
    "\1\157\2\0\1\157\1\221\6\0\1\221\61\0\1\157"+
    "\1\0\2\5\5\0\1\222\1\5\4\0\27\5\27\0"+
    "\1\5\1\0\2\5\5\0\1\223\1\5\4\0\27\5"+
    "\27\0\1\5\13\102\1\165\1\224\60\102\1\0\2\5"+
    "\5\0\2\5\4\0\14\5\1\225\12\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\2\5\1\226\24\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\10\5"+
    "\1\227\16\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\16\5\1\230\10\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\5\5\1\231\1\232\20\5\27\0"+
    "\1\5\1\0\2\5\5\0\1\233\1\5\4\0\27\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\7\5"+
    "\1\234\17\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\2\5\1\235\24\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\14\5\1\236\12\5\27\0\1\5"+
    "\1\0\2\5\5\0\1\237\1\5\4\0\27\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\6\5\1\240"+
    "\20\5\27\0\1\5\1\0\2\5\5\0\1\241\1\5"+
    "\4\0\27\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\1\5\1\242\25\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\12\5\1\243\14\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\1\5\1\244\25\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\10\5"+
    "\1\245\16\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\1\246\26\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\10\5\1\247\16\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\5\5\1\250\21\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\3\5\1\251"+
    "\23\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\13\5\1\252\13\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\26\5\1\235\27\0\1\5\2\0\1\253"+
    "\1\254\6\0\1\254\61\0\1\253\2\0\1\253\71\0"+
    "\1\253\1\0\2\5\5\0\2\5\4\0\7\5\1\255"+
    "\17\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\4\5\1\256\22\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\11\5\1\257\15\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\6\5\1\260\20\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\14\5\1\261"+
    "\12\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\4\5\1\262\22\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\1\5\1\263\25\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\3\5\1\264\23\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\7\5\1\265"+
    "\17\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\7\5\1\266\17\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\12\5\1\267\14\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\2\5\1\270\24\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\6\5\1\271"+
    "\20\5\27\0\1\5\1\0\2\5\5\0\1\272\1\5"+
    "\4\0\27\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\6\5\1\273\20\5\27\0\1\5\2\0\1\253"+
    "\1\221\6\0\1\221\61\0\1\253\1\0\2\5\5\0"+
    "\2\5\4\0\4\5\1\274\22\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\275\22\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\16\5\1\276"+
    "\10\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\15\5\1\277\11\5\27\0\1\5\1\0\2\5\5\0"+
    "\2\5\4\0\20\5\1\300\6\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\13\5\1\301\13\5\27\0"+
    "\1\5\1\0\2\5\5\0\2\5\4\0\4\5\1\302"+
    "\22\5\27\0\1\5\1\0\2\5\5\0\2\5\4\0"+
    "\2\5\1\303\24\5\27\0\1\5\1\0\2\5\5\0"+
    "\1\304\1\5\4\0\27\5\27\0\1\5\1\0\2\5"+
    "\5\0\2\5\4\0\14\5\1\305\12\5\27\0\1\5"+
    "\1\0\2\5\5\0\2\5\4\0\12\5\1\306\14\5"+
    "\27\0\1\5\1\0\2\5\5\0\2\5\4\0\6\5"+
    "\1\307\20\5\27\0\1\5\1\0\2\5\5\0\2\5"+
    "\4\0\1\5\1\310\25\5\27\0\1\5\1\0\2\5"+
    "\5\0\1\311\1\5\4\0\27\5\27\0\1\5\1\0"+
    "\2\5\5\0\2\5\4\0\4\5\1\312\22\5\27\0"+
    "\1\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7808];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\0\1\11\3\1\1\11\27\1\4\11"+
    "\1\1\15\11\1\1\1\11\4\1\2\0\2\11\3\1"+
    "\2\11\1\1\1\0\1\11\33\1\17\11\1\0\1\1"+
    "\2\0\3\1\1\0\32\1\2\0\32\1\1\0\36\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuilder string;
    StringBuilder character;

    private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
    	return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 194) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol scanFunction() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }  // fall though
            case 203: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { string.append( yytext() );
            } 
            // fall through
          case 84: break;
          case 2: 
            { throw new Error("Illegal character <" + yytext() + ">");
            } 
            // fall through
          case 85: break;
          case 3: 
            { return symbol(sym.ID, new String(yytext()));
            } 
            // fall through
          case 86: break;
          case 4: 
            { return symbol(sym.INTCONST, new Integer(yytext()));
            } 
            // fall through
          case 87: break;
          case 5: 
            { return symbol(sym.MINUS);
            } 
            // fall through
          case 88: break;
          case 6: 
            { 
            } 
            // fall through
          case 89: break;
          case 7: 
            { return symbol(sym.ADD);
            } 
            // fall through
          case 90: break;
          case 8: 
            { return symbol(sym.DIV);
            } 
            // fall through
          case 91: break;
          case 9: 
            { return symbol(sym.ASSIGN);
            } 
            // fall through
          case 92: break;
          case 10: 
            { return symbol(sym.LESS);
            } 
            // fall through
          case 93: break;
          case 11: 
            { return symbol(sym.GR);
            } 
            // fall through
          case 94: break;
          case 12: 
            { return symbol(sym.BITNEG);
            } 
            // fall through
          case 95: break;
          case 13: 
            { return symbol(sym.ARITHAND);
            } 
            // fall through
          case 96: break;
          case 14: 
            { return symbol(sym.ARITHOR);
            } 
            // fall through
          case 97: break;
          case 15: 
            { return symbol(sym.XOR);
            } 
            // fall through
          case 98: break;
          case 16: 
            { return symbol(sym.PROD);
            } 
            // fall through
          case 99: break;
          case 17: 
            { return symbol(sym.MOD);
            } 
            // fall through
          case 100: break;
          case 18: 
            { return symbol(sym.LCURLY);
            } 
            // fall through
          case 101: break;
          case 19: 
            { return symbol(sym.RCURLY);
            } 
            // fall through
          case 102: break;
          case 20: 
            { return symbol(sym.LPAREN);
            } 
            // fall through
          case 103: break;
          case 21: 
            { return symbol(sym.RPAREN);
            } 
            // fall through
          case 104: break;
          case 22: 
            { return symbol(sym.DOT);
            } 
            // fall through
          case 105: break;
          case 23: 
            { return symbol(sym.COMMA);
            } 
            // fall through
          case 106: break;
          case 24: 
            { return symbol(sym.COLON);
            } 
            // fall through
          case 107: break;
          case 25: 
            { return symbol(sym.SEMICOLON);
            } 
            // fall through
          case 108: break;
          case 26: 
            { return symbol(sym.LBRACK);
            } 
            // fall through
          case 109: break;
          case 27: 
            { return symbol(sym.RBRACK);
            } 
            // fall through
          case 110: break;
          case 28: 
            { string = new StringBuilder("\""); yybegin(STRING);
            } 
            // fall through
          case 111: break;
          case 29: 
            { character = new StringBuilder("\'"); yybegin(CHAR);
            } 
            // fall through
          case 112: break;
          case 30: 
            { string.append("\"");
	    yybegin(YYINITIAL);
	    return symbol(sym.STRINGCONST, new String(string.toString()));
            } 
            // fall through
          case 113: break;
          case 31: 
            { string.append("\\");
            } 
            // fall through
          case 114: break;
          case 32: 
            { character.append(yytext());
	    yybegin(YYINITIAL);
	    return symbol(sym.CHARCONST, new Character(character.toString().charAt(1)));
            } 
            // fall through
          case 115: break;
          case 33: 
            { return symbol(sym.DEC);
            } 
            // fall through
          case 116: break;
          case 34: 
            { return symbol(sym.SUBASS);
            } 
            // fall through
          case 117: break;
          case 35: 
            { return symbol(sym.INC);
            } 
            // fall through
          case 118: break;
          case 36: 
            { return symbol(sym.ADDASS);
            } 
            // fall through
          case 119: break;
          case 37: 
            { return symbol(sym.DIVASS);
            } 
            // fall through
          case 120: break;
          case 38: 
            { return symbol(sym.LOGICOR);
            } 
            // fall through
          case 121: break;
          case 39: 
            { return symbol(sym.IF);
            } 
            // fall through
          case 122: break;
          case 40: 
            { return symbol(sym.EQ);
            } 
            // fall through
          case 123: break;
          case 41: 
            { return symbol(sym.NOTEQ);
            } 
            // fall through
          case 124: break;
          case 42: 
            { return symbol(sym.LESSEQ);
            } 
            // fall through
          case 125: break;
          case 43: 
            { return symbol(sym.GREQ);
            } 
            // fall through
          case 126: break;
          case 44: 
            { return symbol(sym.MULTASS);
            } 
            // fall through
          case 127: break;
          case 45: 
            { string.append("\\b");
            } 
            // fall through
          case 128: break;
          case 46: 
            { string.append("\\n");
            } 
            // fall through
          case 129: break;
          case 47: 
            { string.append("\\t");
            } 
            // fall through
          case 130: break;
          case 48: 
            { string.append("\\r");
            } 
            // fall through
          case 131: break;
          case 49: 
            { string.append("\\f");
            } 
            // fall through
          case 132: break;
          case 50: 
            { string.append("\\v");
            } 
            // fall through
          case 133: break;
          case 51: 
            { string.append("\\\"");
            } 
            // fall through
          case 134: break;
          case 52: 
            { string.append("\\\'");
            } 
            // fall through
          case 135: break;
          case 53: 
            { string.append("\\0");
            } 
            // fall through
          case 136: break;
          case 54: 
            { return symbol(sym.REALCONST, new Double(yytext()));
            } 
            // fall through
          case 137: break;
          case 55: 
            { return symbol(sym.END);
            } 
            // fall through
          case 138: break;
          case 56: 
            { return symbol(sym.NOT);
            } 
            // fall through
          case 139: break;
          case 57: 
            { return symbol(sym.LOGICAND);
            } 
            // fall through
          case 140: break;
          case 58: 
            { return symbol(sym.INT);
            } 
            // fall through
          case 141: break;
          case 59: 
            { return symbol(sym.FOR);
            } 
            // fall through
          case 142: break;
          case 60: 
            { return symbol(sym.ELSE);
            } 
            // fall through
          case 143: break;
          case 61: 
            { return symbol(sym.BOOL);
            } 
            // fall through
          case 144: break;
          case 62: 
            { return symbol(sym.LONG);
            } 
            // fall through
          case 145: break;
          case 63: 
            { return symbol(sym.CASE);
            } 
            // fall through
          case 146: break;
          case 64: 
            { return symbol(sym.CHAR);
            } 
            // fall through
          case 147: break;
          case 65: 
            { return symbol(sym.NULL);
            } 
            // fall through
          case 148: break;
          case 66: 
            { return symbol(sym.TRUE);
            } 
            // fall through
          case 149: break;
          case 67: 
            { return symbol(sym.AUTO);
            } 
            // fall through
          case 150: break;
          case 68: 
            { return symbol(sym.VOID);
            } 
            // fall through
          case 151: break;
          case 69: 
            { return symbol(sym.BEGIN);
            } 
            // fall through
          case 152: break;
          case 70: 
            { return symbol(sym.BREAK);
            } 
            // fall through
          case 153: break;
          case 71: 
            { return symbol(sym.CONST);
            } 
            // fall through
          case 154: break;
          case 72: 
            { return symbol(sym.FLOAT);
            } 
            // fall through
          case 155: break;
          case 73: 
            { return symbol(sym.FALSE);
            } 
            // fall through
          case 156: break;
          case 74: 
            { return symbol(sym.EXTERN);
            } 
            // fall through
          case 157: break;
          case 75: 
            { return symbol(sym.STRING);
            } 
            // fall through
          case 158: break;
          case 76: 
            { return symbol(sym.SIZEOF);
            } 
            // fall through
          case 159: break;
          case 77: 
            { return symbol(sym.SWITCH);
            } 
            // fall through
          case 160: break;
          case 78: 
            { return symbol(sym.RECORD);
            } 
            // fall through
          case 161: break;
          case 79: 
            { return symbol(sym.RETURN);
            } 
            // fall through
          case 162: break;
          case 80: 
            { return symbol(sym.DOUBLE);
            } 
            // fall through
          case 163: break;
          case 81: 
            { return symbol(sym.DEFAULT);
            } 
            // fall through
          case 164: break;
          case 82: 
            { return symbol(sym.CONTINUE);
            } 
            // fall through
          case 165: break;
          case 83: 
            { return symbol(sym.FUNCTION);
            } 
            // fall through
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
